definitions:
  handler.request:
    properties:
      amount:
        description: binding:"required"`
        type: number
      cod:
        description: a la de la entidad sin el ID
        type: string
      currency:
        description: binding:"required"`
        type: string
      date:
        description: binding:"required"`
        type: string
      receiver:
        description: binding:"required"`
        type: string
      sender:
        description: binding:"required"`
        type: string
    type: object
  web.Response:
    properties:
      code:
        type: string
      data: {}
      error:
        type: string
    type: object
info:
  contact:
    name: API Support
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This API handle transactions
  termsOfService: https://developers.mercadolibre.com.ar/es_ar/terminos-y-condiciones
  title: MELI Bootcamp Go W6 - API
  version: "4.2"
paths:
  /transactions:
    get:
      description: get transactions from json db file
      produces:
      - application/json
      responses:
        "200":
          description: List Transactions
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Transactions not found
          schema:
            $ref: '#/definitions/web.Response'
      summary: List existing transactions
      tags:
      - Transactions
    post:
      consumes:
      - application/json
      description: post new Transaction and save into de db json file
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Transaction to store
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses:
        "200":
          description: Transaction Stored
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: Invalid parameter
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
      summary: List new Transaction
      tags:
      - Transactions
  /transactions/{ID}:
    delete:
      description: Delete an existing Transaction of the db json file
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Transaction Deleted
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: Invalid parameter
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Transaction not found
          schema:
            $ref: '#/definitions/web.Response'
      summary: Delete Transaction
      tags:
      - Transactions
    patch:
      consumes:
      - application/json
      description: update cod and amount parameters of an existing Transaction of
        the db json file
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: New paramaters to update the existing Transaction
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses:
        "200":
          description: cod and amount Transaction Updated
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: Invalid parameter
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Transaction not found
          schema:
            $ref: '#/definitions/web.Response'
      summary: Partial Update on a Transaction
      tags:
      - Transactions
    put:
      consumes:
      - application/json
      description: update all the parameters of an existing Transaction of the db
        json file
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: New paramaters to update the existing Transaction
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses:
        "200":
          description: Transaction Updated
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: Invalid parameter
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Transaction not found
          schema:
            $ref: '#/definitions/web.Response'
      summary: Update Transaction
      tags:
      - Transactions
swagger: "2.0"
